Created toasts that are displayed for 3000 ms, unless someone hovers …
Alkowskey/BaseAngular pull request #14
Opened 2021-12-28 12:12 UTC by Alkowskey

…over them

2021-12-28 12:15 UTC, Alkowskey commented on src/app/services/notification.service.ts
> +      this.next([...this.value, notification])
not really sure what it does, gonna read about it but seems weird

2021-12-28 12:15 UTC, Alkowskey commented on src/app/services/notification.service.ts
> +        this.next(this.value.filter(item => item !== notification))
same with line 23

2022-01-05 08:40 UTC, EugeneHerasymchuk requested changes

2022-01-05 08:40 UTC, EugeneHerasymchuk commented on src/app/services/notification.service.ts
> +export class NotificationService extends BehaviorSubject<readonly Notification<any, any>[]> {
this we can discuss on the call, a bit not usual approach

2022-01-17 09:30 UTC, merged